### PR TITLE
fix: use most updated network for validators

### PR DESCRIPTION
**Pull request by pdp2121**
## High Level Overview of Change

`Validators` table is updating networks with comma-separated. This change will keep only the most updated one.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by mvadari** [comment]
lgtm, assuming it fixes the issue in staging - holding off on ✅ until then

**Comment by ckniffen** [comment]
Is #53 also needed?  I think it makes sense to combine with it.

**Comment by pdp2121** [comment]
> Is #53 also needed? I think it makes sense to combine with it.

Yes I think it makes sense to just keep one network for both nodes and validators. @mvadari what do you think?

**Review by mvadari — APPROVED** [review]

**Comment by mvadari** [comment]
> > Is #53 also needed? I think it makes sense to combine with it.
> 
> Yes I think it makes sense to just keep one network for both nodes and validators. @mvadari what do you think?

I agree - we should just use the same policy for both. Though I do think it'll be easier to test in prod if we only use this policy for one of the two for a couple months, just to see how it looks.

**Comment by pdp2121** [comment]
> > > Is #53 also needed? I think it makes sense to combine with it.
> > 
> > 
> > Yes I think it makes sense to just keep one network for both nodes and validators. @mvadari what do you think?
> 
> I agree - we should just use the same policy for both. Though I do think it'll be easier to test in prod if we only use this policy for one of the two for a couple months, just to see how it looks.

Okay I will deploy this first and hold off on #53 for like a month to see how it goes.

**Review by ckniffen — APPROVED** [review]

**Pull request merged**
